"""reviewed baseline for existing application schema

Revision ID: 20260308_0001
Revises:
Create Date: 2026-03-08 18:30:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260308_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Stamp-only baseline.

    This revision intentionally performs no DDL.

    Rationale:
    - the repo has pre-existing one-off migration scripts
    - the authoritative schema has already evolved outside Alembic
    - freezing a giant autogenerated bootstrap here would create false confidence

    Usage:
    - existing databases should be stamped to this baseline after validation
    - all future schema changes should build forward from this revision
    """
    pass


def downgrade() -> None:
    """No-op downgrade for baseline stamp revision."""
    pass
